export default {
    "code": "zh_TW",
    "messages": {
      "alpha": "{_field_} 需以英文組成",
      "alpha_dash": "{_field_} 需以英數、斜線及底線組成",
      "alpha_num": "{_field_} 需以英數組成",
      "alpha_spaces": "{_field_} 需以英文及空格組成",
      "between": "{_field_} 需介於 {min} 至 {max}之間",
      "confirmed": " {_field_} 不一致",
      "digits": "{_field_} 需為 {length} 位數字",
      "dimensions": "{_field_} 圖片尺寸不正確。需為 {width} x {height} 像素",
      "email": "請填寫正確的電子信箱",
      "excluded": "{_field_} 的選項無效",
      "ext": "{_field_} 需為有效的檔案",
      "image": "{_field_} 需為圖片",
      "oneOf": "{_field_} 的選項無效",
      "integer": "{_field_} 需為整數",
      "length": "{_field_} 需為 {length} 碼",
      "max": "{_field_} 不能大於 {length} 個字元",
      "max_value": "{_field_} 不得大於 {max}",
      "mimes": "{_field_} 需為有效的檔案類型",
      "min": "{_field_} 不能小於 {length} 個字元",
      "min_value": "{_field_}不得小於 {min}",
      "numeric": "{_field_} 需為數字",
      "regex": "{_field_} 的格式錯誤",
      "required": "請填寫{_field_}",
      "required_if": "{_field_} 為必填",
      "size": "{_field_} 的檔案需小於 {size}KB"
    }
}